services:
  app:
    build: .
    container_name: symfony-app
    volumes:
      - ./var:/var/www/symfony/var:rw
      - ./public/media:/var/www/symfony/public/media:rw
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/var/www/symfony/public:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    environment:
      - SYMFONY_ENV=prod
      - APP_ENV=prod
      - APP_DEBUG=0
    ports:
      - "81:80"
      - "444:443"
