services:
  app:
    build: .
    container_name: symfony-app
    volumes:
      - ./var:/var/www/symfony/var:rw
      - ./media:/var/www/symfony/media:rw
      - ./nginx/certs:/etc/nginx/certs:ro
    environment:
      - SYMFONY_ENV=prod
      - APP_ENV=prod
      - APP_DEBUG=0
      - DATABASE_URL="postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}/${DB_NAME}?serverVersion=16&charset=utf8"
      - DEFAULT_URI=http://localhost
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: symfony-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
    driver: local