services:
  app:
    build: .
    container_name: symfony-app
    volumes:
      - ./var:/var/www/symfony/var:rw
      - ./public/media:/var/www/symfony/public/media:rw
      - ./nginx/certs:/etc/nginx/certs:ro
    environment:
      - SYMFONY_ENV=prod
      - APP_ENV=prod
      - APP_DEBUG=0
      - DATABASE_URL=sqlite:///%kernel.project_dir%/var/data_%kernel.environment%.db
      - DEFAULT_URI=http://localhost
    ports:
      - "80:80"
      - "443:443"
